on:
  schedule:
    - cron: "0 0 * * *"
  push: 
    branches: 
      - main 
      
name: databuild 

jobs:
  render:
    name: databuild
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with: 
          r-version: '4.0.2'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "tidyr", "lubridate", "here", "googledrive", "googlesheets4"))
        shell: Rscript {0}
      - name: Build data
        run: Rscript -e 'source("R/dat_build.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build baby data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"