on:
  schedule:
    - cron: "0 0 * * *"
  push: 
    branches: 
      - main 

name: reportbuild

jobs:
  render:
    name: reportbuild
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install R packages
        run: |
          install.packages(c("dplyr", "tidyr", "lubridate", "here", "ggplot2", "reactable", "plotly", "knitr", "rmarkdown"))
        shell: Rscript {0}
      - name: Render index
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"